### ISSUE TITLE
Node.js Pet SNS - Middelware issue

### ISSUE THREAD

**Issue by July249** [July249/likelion_fe_school_3#6]
eaf1378296e7a9bda3fba6e97b326a9caa565a84

```bash
C:\Users\JihyeongLee\Desktop\Projects\likelion_fe_school_3\online_course\node-js\pet-sns\node_modules\express\lib\router\index.js:458
      throw new TypeError('Router.use() requires a middleware function but got a ' + gettype(fn))
      ^

TypeError: Router.use() requires a middleware function but got a Object     
    at Function.use (C:\Users\JihyeongLee\Desktop\Projects\likelion_fe_school_3\online_course\node-js\pet-sns\node_modules\express\lib\router\index.js:458:13)
    at Object.<anonymous> (C:\Users\JihyeongLee\Desktop\Projects\likelion_fe_school_3\online_course\node-js\pet-sns\routes\index.js:10:8)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)      
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\JihyeongLee\Desktop\Projects\likelion_fe_school_3\online_course\node-js\pet-sns\app.js:7:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
```

**Comment by July249** [comment]
Simple typo error => Now, no more error!

**Comment by July249** [comment]
Simple typo error => Now, no more error!
